# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9197855b74691d4044a790dea8ac55c82058c2e97b0589398f15c51b06474a86c5a149a45d5533e354835165bd852dd5671f273325697e1bfe85a3b5ba56eb4

test:
  secret_key_base: db275f6dcd1262c6b5e093019a00e3f0307a36a1e63173aee2bd19214824d99d0e76d8c781856874c345c00219522a4d232f29ed8b94074e0030677eea61ed8a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
